### ISSUE TITLE
Dependancy missing?

### ISSUE THREAD

**Issue by LilyIsTrans** [shadwork/Windows-Crunch#2]
When I run cl crunch.c it says unisted.h doesn't exist, even with the flag -IC:
Am I missing a file?
  Edit: I am running windows, in case that's important.

**Comment by onix-adt** [comment]
You mean cl.exe compiler from Visual Studio ? unistd.h come from original project, that running on linux.
This project target to [Mingw](http://www.mingw.org) compiler that already have unistd.h, so if you want compile under this compiler you must add some wrappers to linux headers.
You can start with adding [Windows unistd.h replacement](https://gist.github.com/mbikovitsky/39224cf521bfea7eabe9)

**Comment by LilyIsTrans** [comment]
Thanks!
